module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Ancestor',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Spirit',
    'Dusty',
    'Diamond',
    'Silver',
    'Blackwood',
    'Alpine',
    'Red',
    'Outback',
    'Calmwater',
    'Saltside',
    'Goldwater',
    'Hardland',
    'Serpent',
    'Coyote',
    'Badger',
    'Ashland',
    "Giant's",
    'Moonbeam',
    'Copper Rush',
    'Sunspot',
    'Gilded',
    'Cooke'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Oaks',
    'Group Camp',
    'Glade',
    'Horse Camp',
    'Ghost Town',
    'Rest',
    'Grove',
    'Fields',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'Grotto',
    'Arbor',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Meadow',
    'Watermill',
    'Lumber Camp',
    'Range',
    'Narrows',
    'Plains',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Cliffside',
    'Outpost',
    'Site',
    'Hollow',
    'Geyser',
    'Hotsprings',
    'Lake'
]

